### PR TITLE
Generate secret references for the sensitive fields under the spec.initProvider API tree

### PR DESCRIPTION
**Pull request by ulucinar**
### Description of your changes

Depends on: https://github.com/crossplane/upjet/pull/411

This PR bumps upjet to commit `f4f87bab8535` from https://github.com/crossplane/upjet/pull/411 and generates the secret references for the sensitive fields under the `spec.initProvider` API tree. For further context, please refer to https://github.com/crossplane/upjet/pull/406. 

This PR also uses the `traverser.maxItemsSync` schema traverser introduced in https://github.com/crossplane/upjet/pull/411 to sync the `MaxItems` constraints from the Go schema to the JSON schema. For the current set of configured resources in the provider, this is currently not an issue but we are implementing automatic syncing of this constraint (until the JSON schema usage is removed in a major version bump) in case any future resources will need it.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

Via uptest: https://github.com/crossplane-contrib/provider-upjet-azuread/actions/runs/9487439963

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by ulucinar** [comment]
/test-examples="examples/applications/v1beta2/application.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @ulucinar LGTM!

**Comment by ulucinar** [comment]
/test-examples="examples/applications/v1beta2/application.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/applications/v1beta2/application.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/applications/v1beta2/application.yaml"

**Pull request merged**
