### PR TITLE
Introduce MR metrics

### PR DESCRIPTION
**Pull request by mergenci**
### Description of your changes

Consume https://github.com/crossplane/crossplane-runtime/pull/683 and https://github.com/crossplane/upjet/pull/390.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

Successfully observed the new metrics by provisioning the example manifest `examples/applications/application.yaml`.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by mergenci** [comment]
/test-examples="examples/users/v1beta1/user.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/users/user.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/users/user.yaml"

**Review by ulucinar — APPROVED** [review]
Thanks @mergenci, lgtm.

**Pull request merged**
