### PR TITLE
Bump Upjet to commit 2e361ad3b6e6

### PR DESCRIPTION
**Pull request by mergenci**
### Description of your changes

Bump Upjet to latest version: https://github.com/crossplane/upjet/commit/2e361ad3b6e6b225bbc560ecf7c92e88a7c3ae3a

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR if necessary.~

### How has this code been tested

See Uptest runs below:

1. [/test-examples="examples/applications/v1beta2/application.yaml"](https://github.com/crossplane-contrib/provider-upjet-azuread/actions/runs/10510762504)
2. [/test-examples="examples/conditionalaccess/v1beta2/location.yaml"](https://github.com/crossplane-contrib/provider-upjet-azuread/actions/runs/10510768140)
3. [/test-examples="examples/groups/v1beta1/group.yaml"](https://github.com/crossplane-contrib/provider-upjet-azuread/actions/runs/10510772488)
4. [/test-examples="examples/groups/v1beta2/group.yaml"](https://github.com/crossplane-contrib/provider-upjet-azuread/actions/runs/10510773422)

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by mergenci** [comment]
/test-examples="examples/applications/v1beta2/application.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/conditionalaccess/v1beta2/location.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/groups/v1beta1/group.yaml"

**Comment by mergenci** [comment]
/test-examples="examples/groups/v1beta2/group.yaml"

**Review by turkenf — APPROVED** [review]
Thank you @mergenci, LGTM.

**Pull request merged**
