### PR TITLE
Change the value of meta.crossplane.io/source

### PR DESCRIPTION
**Pull request by sergenyalcin**
### Description of your changes

This PR changes the value of `meta.crossplane.io/source` to fix the source code link.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by turkenf** [comment]
/test-examples="examples/administrativeunits/unit.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/app/roleassignment.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/applications/application.yaml"

**Review by ulucinar — APPROVED** [review]
Thanks @sergenyalcin, lgtm.

**Review by turkenf — APPROVED** [review]
Thank you @sergenyalcin, LGTM.

**Pull request merged**
