### PR TITLE
Bump upjet to the commit 3afbb77

### PR DESCRIPTION
**Pull request by turkenf**
### Description of your changes

This PR bump upjet to the commit `3afbb77`, which [fixes](https://github.com/crossplane/upjet/pull/435) the issue of hiding error messages.

Fixes https://github.com/crossplane-contrib/provider-upjet-azuread/issues/153

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

- `examples/applications/v1beta2/application.yaml` => https://github.com/crossplane-contrib/provider-upjet-azuread/actions/runs/10831056297
- `examples/conditionalaccess/v1beta2/location.yaml` => https://github.com/crossplane-contrib/provider-upjet-azuread/actions/runs/10831053640
- `examples/groups/v1beta1/group.yaml` => https://github.com/crossplane-contrib/provider-upjet-azuread/actions/runs/10831055192

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by turkenf** [comment]
/test-examples="examples/conditionalaccess/v1beta2/location.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/groups/v1beta1/group.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/applications/v1beta2/application.yaml"

**Review by mergenci — APPROVED** [review]
Thanks @turkenf. LGTM.

**Pull request merged**
