### PR TITLE
Use standalone crddiff tool

### PR DESCRIPTION
**Pull request by turkenf**
### Description of your changes

This PR uses the standalone `crddiff` tool.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR if necessary.~

### How has this code been tested

Tested with the uptest in the below comments.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by turkenf** [comment]
/test-examples="examples/applications/v1beta1/application.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/conditionalaccess/v1beta2/accesspolicy.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/applications/v1beta1/application.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/conditionalaccess/v1beta2/accesspolicy.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/applications/v1beta1/application.yaml"

**Review by mergenci — APPROVED** [review]
Thanks @turkenf 🙌 LGTM. For posterity, `crddiff` used to be a command-line argument to `uptest`. `crddiff` didn't fit `uptest`'s purpose in the first place, so it was removed before donating `uptest` to the community. Now that we have updated the build module to use crossplane/build, which doesn't have `crddiff`, we are running it from upbound/uptest.

**Pull request merged**
