### PR TITLE
Update Terraform provider version to 2.53.1

### PR DESCRIPTION
**Pull request by erhancagirici**
### Description of your changes
Updated Terraform provider version to 2.53.1
This PR is recreated from [original PR](https://github.com/crossplane-contrib/provider-upjet-azuread/pull/148) by community, to move forward with changes.

Adjusted the go version to 1.23 and golangci-lint version to 1.61.0 in CI job.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested
`make reviewable test` and uptest

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by erhancagirici** [comment]
/test-examples="examples/app/v1beta1/roleassignment.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/serviceprincipals/v1beta1/principal.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/applications/v1beta1/application.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/applications/v1beta1/password.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/administrativeunits/v1beta1/unit.yaml"

**Review by turkenf — APPROVED** [review]
Thank you @erhancagirici, LGTM 🙌

**Pull request merged**
